# Generated by Django 5.0 on 2025-07-05 13:45

from django.db import migrations


def copy_profile_data_from_oc_lettings_site(apps, schema_editor):
    # Get the old and new models
    OldProfile = apps.get_model("oc_lettings_site", "Profile")
    NewProfile = apps.get_model("profiles", "Profile")

    # Copy Profile data
    for old_profile in OldProfile.objects.all():
        NewProfile.objects.create(
            id=old_profile.id,
            user=old_profile.user,
            favorite_city=old_profile.favorite_city,
        )


def reverse_copy_profile_data(apps, schema_editor):
    # Remove data from new table
    NewProfile = apps.get_model("profiles", "Profile")
    NewProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("oc_lettings_site", "0001_initial"),  # Ensure old model is available
    ]

    operations = [
        migrations.RunPython(
            copy_profile_data_from_oc_lettings_site, reverse_copy_profile_data
        ),
    ]
