# Generated by Django 5.0 on 2025-07-05 13:42

from django.db import migrations


def copy_data_from_oc_lettings_site(apps, schema_editor):
    # Get the old and new models
    OldAddress = apps.get_model("oc_lettings_site", "Address")
    OldLetting = apps.get_model("oc_lettings_site", "Letting")
    NewAddress = apps.get_model("lettings", "Address")
    NewLetting = apps.get_model("lettings", "Letting")

    # Copy Address data
    for old_address in OldAddress.objects.all():
        NewAddress.objects.create(
            id=old_address.id,
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code,
        )

    # Copy Letting data
    for old_letting in OldLetting.objects.all():
        # Get the corresponding new address
        new_address = NewAddress.objects.get(id=old_letting.address.id)
        NewLetting.objects.create(
            id=old_letting.id, title=old_letting.title, address=new_address
        )


def reverse_copy_data(apps, schema_editor):
    # Remove data from new tables
    NewAddress = apps.get_model("lettings", "Address")
    NewLetting = apps.get_model("lettings", "Letting")
    NewAddress.objects.all().delete()
    NewLetting.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("lettings", "0001_initial"),
        ("oc_lettings_site", "0001_initial"),  # Ensure old models are available
    ]

    operations = [
        migrations.RunPython(copy_data_from_oc_lettings_site, reverse_copy_data),
    ]
