# Generated by Django 5.0 on 2025-07-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oc_lettings_site", "0001_initial"),
        (
            "lettings",
            "0002_copy_data_from_oc_lettings_site",
        ),  # Ensure data is copied first
    ]

    operations = [
        migrations.RemoveField(
            model_name="letting",
            name="address",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="Letting",
        ),
    ]
