# Generated by Django 5.0 on 2025-07-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "oc_lettings_site",
            "0002_remove_letting_address_delete_address_delete_letting",
        ),
        ("profiles", "0002_copy_profile_data_from_oc_lettings_site"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
